// constants/courseFields.js
import { lecturersData } from "../data/lecturersData";

export const courseFields = [
	{
		id: "course-code",
		name: "id",
		label: "Course Code",
		type: "text",
		placeholder: "e.g., SEN 111",
		colSpan: 1,
	},
	{
		id: "course-units",
		name: "units",
		label: "Credit Units",
		type: "select",
		placeholder: "Select units",
		colSpan: 1,
		options: ["1", "2", "3", "4", "5", "6"],
	},
	{
		id: "course-title",
		name: "title",
		label: "Course Title",
		type: "text",
		placeholder: "Enter course title",
		colSpan: 2,
	},
	{
		id: "course-department",
		name: "department",
		label: "Department",
		type: "select",
		placeholder: "Select department",
		colSpan: 1,
		options: [
			"Software Engineering",
			"Computer Science",
			"Mechanical Engineering",
			"Electrical Engineering",
			"Civil Engineering",
			"Business Administration",
			"Accounting",
			"Petroleum Engineering",
		],
	},
	{
		id: "course-level",
		name: "level",
		label: "Level",
		type: "select",
		placeholder: "Select level",
		colSpan: 1,
		options: ["100", "200", "300", "400", "500"],
	},
	{
		id: "course-lecturer",
		name: "lecturerName",
		label: "Assigned Lecturer",
		type: "select",
		placeholder: "Select lecturer",
		colSpan: 1,
		options: lecturersData.map((l) => `${l.prefix} ${l.name}`),
	},
	{
		id: "course-semester",
		name: "semester",
		label: "Semester",
		type: "select",
		placeholder: "Select semester",
		colSpan: 1,
		options: ["First Semester", "Second Semester"],
	},
];
